config/routes.rb
Rails.application.routes.draw do
  # トップページ
  root to: 'tops#index'

  # devise関連(shop_user)
  devise_for :shop_users, skip: :all

  devise_scope :shop_user do
    get 'login' => 'shop_users/sessions#new', as: :new_shop_user_session
    post 'login' => 'shop_users/sessions#create', as: :shop_user_session
    delete 'logout' => 'shop_users/sessions#destroy', as: :destroy_shop_user_session
    get 'signup' => 'shop_users/registrations#new', as: :new_shop_user_registration
    post "sign_up/confirm" => "shop_users/registrations#confirm", as: :confirm_shop_user_registration
    post 'signup' => 'shop_users/registrations#create', as: :shop_user_registration
    # get 'signup/cancel' => 'shop_users/registrations#cancel', as: :cancel_shop_user_registration
    get '/:shop_user_id/shop_user' => 'shop_users/registrations#show', as: :show_shop_user_registration
    get '/:shop_user_id/shop_user/edit' => 'shop_users/registrations#edit', as: :edit_shop_user_registration
    patch '/:shop_user_id/shop_user/update' => 'shop_users/registrations#update', as: :update_shop_user_registration
    # put 'user' => 'shop_users/registrations#update', as: :update_shop_user_registration
    delete 'user' => 'shop_users/registrations#destroy', as: :destroy_shop_user_registration
    get 'password' => 'shop_users/passwords#new', as: :new_shop_user_password
    post 'password' => 'shop_users/passwords#create', as: :shop_user_password
    get 'password/edit' => 'shop_users/passwords#edit', as: :edit_shop_user_password
    patch 'password' => 'shop_users/passwords#update'
    put 'password' => 'shop_users/passwords#update', as: :update_shop_user_password
  end
  resources :shop_users

  # 店舗関連
  controller :stores do
    scope path: ':shop_user_id' do
      resources :stores do
        post 'confirm', on: :collection
        # 店舗紐付きの商品関連
        resources :menus
      end
    end
  end
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :store
  mount_uploader :image, ImageUploader
end

app/controllers/menus_controller.rb
class MenusController < StoresController

  def index
    @menus = Store.current_store(current_shop_user).menus
  end

  def new
	  @menu = Store.current_store(current_shop_user).menus.build
  end


  def create
    @menu = Store.current_store(current_shop_user).menus.build(menu_params)
    if @menu.save
      flash[:notice] = "登録しました。"
      redirect_to store_menus_url
    else
      format.html { render :new }
      format.json { render json: @menu.errors, status: :unprocessable_entity }
      format.js { @status = "fail" }
    end
  end

  def edit
    @menu = Store.current_store(current_shop_user).menus.find(params[:id])
  end

  def update
    @menu = Store.current_store(current_shop_user).menus.find(params[:id])
    if @menu.update(menu_params)
      flash[:notice] = "#{@menu.menu_name}の編集をしました"
      redirect_to store_menus_url
    else
      flash.now[:alert] = "error" # 仮
      render :edit
    end
  end

  def destroy
    @menu = Store.current_store(current_shop_user).menus.find(params[:id])
    @menu.destroy
    flash[:notice] = "削除しました。"
    redirect_to store_menus_url
  end

  private

    def menu_params
      params.require(:menu).permit(:image, :menu_name, :price)
    end

    # def current_store
    #   current_shop_user.store
    # end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <%= form_with(model: [:store, @menu], remote: true) do |f| %>

      <% if @menu.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this user from being saved:</h2>
          <ul>
            <% @menu.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel"><%= title %></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body menu-modal">
        <div class="field">
            <%= f.label :image %>
          <div class="image-field">
            <% if @menu.image.present? %>
              <%= image_tag @menu.image.to_s, size: "200x200" %>
              ➡︎
              <img id="img1" style="width:200px;height:200px;">
            <% else %>
              <img id="img1" style="width:200px;height:200px;">
            <% end %>
            <%= f.file_field :image, id: "menu-file" %>
          </div>
        </div>
        <div class="field">
          <%= f.label :menu_name, class: "form-control-label" %>
          <%= f.text_field :menu_name, class: "form-control menu-input-1" %>
        </div>
        <div class="field">
          <%= f.label :price, class: "form-control-label" %>
          <div class="price-field">
            <%= f.text_field :price, class: "form-control menu-input-2" %>
            <span>&nbsp円(税込み)</span>
          </div>
        </div>
      </div>
      <div class="modal-footer actions">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
        <%= f.submit button, class: "btn btn-primary"%>
      </div>
    <% end %>
  </div>
</div>

<script>
$(function(){
  $('#menu-file').change(function(e){
    //ファイルオブジェクトを取得する
    var file = e.target.files[0];
    var reader = new FileReader();

    //画像でない場合は処理終了
    if(file.type.indexOf("image") < 0){
      alert("画像ファイルを指定してください。");
      return false;
    }

    //アップロードした画像を設定する
    reader.onload = (function(file){
      return function(e){
        $("#img1").attr("src", e.target.result);
        $("#img1").attr("title", file.name);
      };
    })(file);
    reader.readAsDataURL(file);

  });
});
</script>

app/views/menus/edit.js.erb
$("#menu-modal").html("<%= escape_javascript(render partial: 'form', locals: { title: "商品の編集", button: "変更" }) %>");
$("#menu-modal").modal("show");

app/views/menus/index.html.erb
<h2 class="page-title">商品登録</h2>

<div class="">
  <% @menus.each do |menu| %>
    <div class="menu-index">
      <%= image_tag menu.image.to_s, size: "200x200" %><br />
      <div class="">
        <span><%= menu.menu_name %></span>

        <br />
        <span><%= menu.price %>円(税込み)</span>
        <div class="menu-link">
          <%= link_to edit_store_menu_path(id: menu.id), remote: true, class: "menu-edit" do %>
            <i class="fas fa-edit" style="color: #33CC33;"></i>
          <% end %>
          <%= link_to store_menu_path(id: menu.id), method: :delete, data:{ confirm: "#{menu.menu_name}を削除しますか？" }, class: "menu-edit" do %>
            <i class="fas fa-times" style="color: red;"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <%= link_to new_store_menu_path, remote: true, id: "fab", class: "btn btn-success menu-add" do %>
    <i class="fa fa-plus"></i>
  <% end %>
</div>

<!-- モーダル -->
<div class="modal fade" id="menu-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"></div>

app/views/menus/new.js.erb
$("#menu-modal").html("<%= escape_javascript(render partial: 'form', locals: { title: "商品の追加", button: "追加" }) %>");
$("#menu-modal").modal("show");