config/routes.rb
Rails.application.routes.draw do
  # トップページ
  root to: 'tops#index'

  # devise関連(shop_user)
  devise_for :shop_users, skip: :all

  devise_scope :shop_user do
    get 'login' => 'shop_users/sessions#new', as: :new_shop_user_session
    post 'login' => 'shop_users/sessions#create', as: :shop_user_session
    delete 'logout' => 'shop_users/sessions#destroy', as: :destroy_shop_user_session
    get 'signup' => 'shop_users/registrations#new', as: :new_shop_user_registration
    post "sign_up/confirm" => "shop_users/registrations#confirm", as: :confirm_shop_user_registration
    post 'signup' => 'shop_users/registrations#create', as: :shop_user_registration
    # get 'signup/cancel' => 'shop_users/registrations#cancel', as: :cancel_shop_user_registration
    get '/:shop_user_id/shop_user' => 'shop_users/registrations#show', as: :show_shop_user_registration
    get '/:shop_user_id/shop_user/edit' => 'shop_users/registrations#edit', as: :edit_shop_user_registration
    patch '/:shop_user_id/shop_user/update' => 'shop_users/registrations#update', as: :update_shop_user_registration
    # put 'user' => 'shop_users/registrations#update', as: :update_shop_user_registration
    delete 'user' => 'shop_users/registrations#destroy', as: :destroy_shop_user_registration
    get 'password' => 'shop_users/passwords#new', as: :new_shop_user_password
    post 'password' => 'shop_users/passwords#create', as: :shop_user_password
    get 'password/edit' => 'shop_users/passwords#edit', as: :edit_shop_user_password
    patch 'password' => 'shop_users/passwords#update'
    put 'password' => 'shop_users/passwords#update', as: :update_shop_user_password
  end
  resources :shop_users

  # 店舗関連
  controller :stores do
    scope path: ':shop_user_id' do
      resources :stores do
        post 'confirm', on: :collection
        # 店舗紐付きの商品関連
        resources :menus
      end
    end
  end
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :shop_user
  has_one :store_order_info, dependent: :destroy
  has_many :menus
  accepts_nested_attributes_for :store_order_info

  enum prefecture_id:{
    "---":0,
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
    沖縄県:47
  }

  # 現在の店舗レコード取得
  def self.current_store(current_shop_user)
    find_by(shop_user_id: current_shop_user.id)
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_shop_user!
  before_action :store_info_exists, only: [:index]

  def index
  end

  def new
    if current_shop_user.store
      redirect_to store_url(id: current_shop_user.id)
    else
      @store = current_shop_user.build_store
      @store.build_store_order_info
    end
  end

  def confirm
    @store = current_shop_user.build_store(store_params)
    if @store.valid?
      render :confirm
    else
      flash.now[:alert] = "error" # 仮
      render :new
    end
  end

  def create
    @store = current_shop_user.build_store(store_params)
    @store.store_order_info.delivery_reception_conclusion
    render :new and return if params[:back] || !@store.save
    redirect_to stores_url
  end

  def show
    @store = current_shop_user.store
  end

  def edit
    @store = current_shop_user.store
    @store.store_order_info.delivery_reception_edit
  end

  def update
    @store = current_shop_user.store
    render :show and return if params[:back] || !@store.update(store_params)
    @store.store_order_info.delivery_reception_conclusion
    @store.save!
    flash[:notice] = "店舗情報を更新しました。"
    redirect_to store_url
  end

  private

    def store_params
      params.require(:store).permit(:store_name, :phone_num, :post_code, :prefecture_id, :city, :block, :building,
                                      :business_hours_start, :business_hours_finish, :holiday, :home_url,
                                      store_order_info_attributes:[:reception_email, :transport_fee, :delivery_reception_time_1,
                                      :delivery_reception_time_2, :delivery_reception_time_3, :delivery_reception_time_4,
                                      :delivery_reception_time_5, :delivery_reception_time_6, :delivery_reception_time_7,
                                      :delivery_reception_time_1_first, :delivery_reception_time_1_finish,
                                      :delivery_reception_time_2_first, :delivery_reception_time_2_finish,
                                      :delivery_reception_time_3_first, :delivery_reception_time_3_finish,
                                      :delivery_reception_time_4_first, :delivery_reception_time_4_finish,
                                      :delivery_reception_time_5_first, :delivery_reception_time_5_finish,
                                      :delivery_reception_time_6_first, :delivery_reception_time_6_finish,
                                      :delivery_reception_time_7_first, :delivery_reception_time_7_finish,
                                      :comment
                                    ])
    end

    def store_info_exists
      unless current_shop_user.store
        flash[:notice] = "はじめに店舗情報を登録してください。"
        redirect_to new_store_url
      end
    end

end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/confirm.html.erb
<h2 class="page-title">店舗情報登録(内容確認)</h2>

<p>ご登録内容をご確認ください。</p>

<%= form_for(@store, url: stores_path) do |f| %>

  <table class="store-form">
    <tr class="field">
      <td class="label"><%= f.label :store_name %><span>&nbsp※必須</span></td>
      <td class="field">
        <div class="store-confirm"><%= @store.store_name %></div>
        <%= f.hidden_field :store_name, :value => @store.store_name %>
      </td>
    </tr>

    <tr class="field">
      <td class="label"><%= f.label :phone_num %><span>&nbsp※必須</span></td>
      <td class="field">
        <div class="store-confirm"><%= @store.phone_num %></div>
        <%= f.hidden_field :phone_num, :value => @store.phone_num %>
      </td>
    </tr>

    <tr class="field">
      <td class="label"><%= f.label :address %><span>&nbsp※必須</span></td>
      <td class="field address">
        <div class="">
          <%= f.label :post_code %>
          <%= @store.post_code %>
          <%= f.hidden_field :post_code, :value => @store.post_code %>
        </div><br />
        <div class="">
          <%= f.label :prefecture_id %>
          <%= @store.prefecture_id %>
          <%= f.hidden_field :prefecture_id, :value => @store.prefecture_id %>
        </div><br />
        <div class="">
          <%= f.label :city %>
          <%= @store.city %>
          <%= f.hidden_field :city, :value => @store.city %>
        </div><br />
        <div class="">
          <%= f.label :block %>
          <%= @store.block %>
          <%= f.hidden_field :block, :value => @store.block %>
        </div><br />
        <div class="">
          <%= f.label :building %>
          <%= @store.building %>
          <%= f.hidden_field :building, :value => @store.building %>
        </div>
      </td>
    </tr>

    <tr class="field">
      <td class="label"><%= f.label :business_hours %><span>&nbsp※必須</span></td>
      <td class="field">
        <div class="store-confirm">
          <%= @store.business_hours_start.to_s(:time) %>
          <%= f.hidden_field :business_hours_start, :value => @store.business_hours_start %>
          ~
          <%= @store.business_hours_finish.to_s(:time) %>
          <%= f.hidden_field :business_hours_finish, :value => @store.business_hours_finish %>
        </div>
      </td>
    </tr>

    <tr class="field">
      <td class="label"><%= f.label :holiday %><span>&nbsp※必須</span></td>
      <td class="field">
        <div class="store-confirm"><%= @store.holiday %></div>
        <%= f.hidden_field :holiday, :value => @store.holiday %>
      </td>
    </tr>

    <tr class="field">
      <td class="label"><%= f.label :home_url %></td>
      <td class="field">
        <div class="store-confirm"><%= @store.home_url %></div>
        <%= f.hidden_field :home_url, :value => @store.home_url %>
      </td>
    </tr>

  </table>

  <h2 class="page-title2">注文情報</h2>

  <%= f.fields_for :store_order_info do |i| %>

    <table class="store-form">

      <tr class="field">
        <td class="label"><%= i.label :reception_email %><span>&nbsp※必須</span></td>
        <td class="field">
          <div class="store-confirm"><%= @store.store_order_info.reception_email %></div>
          <%= i.hidden_field :reception_email, :value => @store.store_order_info.reception_email %>
        </td>
      </tr>

      <tr class="field">
        <td class="label"><%= i.label :transport_fee %><span>&nbsp※必須</span></td>
        <td class="field">
          <div class="store-confirm"><%= @store.store_order_info.transport_fee %>円</div>
          <%= i.hidden_field :transport_fee, :value => @store.store_order_info.transport_fee %>
        </td>
      </tr>

      <tr class="field">
        <td class="label"><%= i.label :delivery_reception_time %><span>&nbsp※必須</span></td>
        <td class="field delively_reception">
          <%= i.label :delivery_reception_time_1 %>
          <%= @store.store_order_info.delivery_reception_time_1_first.to_s(:time) %>
          <%= i.hidden_field :delivery_reception_time_1_first, :value => @store.store_order_info.delivery_reception_time_1_first %>
          ~
          <%= @store.store_order_info.delivery_reception_time_1_finish.to_s(:time) %>
          <%= i.hidden_field :delivery_reception_time_1_finish, :value => @store.store_order_info.delivery_reception_time_1_finish %><br />


          <%= i.label :delivery_reception_time_2 %>
          <%= @store.store_order_info.delivery_reception_time_2_first.to_s(:time) %>
          <%= i.hidden_field :delivery_reception_time_2_first, :value => @store.store_order_info.delivery_reception_time_2_first %>
          ~
          <%= @store.store_order_info.delivery_reception_time_2_finish.to_s(:time) %>
          <%= i.hidden_field :delivery_reception_time_2_finish, :value => @store.store_order_info.delivery_reception_time_2_finish %><br />

          <%= i.label :delivery_reception_time_3 %>
          <%= @store.store_order_info.delivery_reception_time_3_first.to_s(:time) %>
          <%= i.hidden_field :delivery_reception_time_3_first, :value => @store.store_order_info.delivery_reception_time_3_first %>
          ~
          <%= @store.store_order_info.delivery_reception_time_3_finish.to_s(:time) %>
          <%= i.hidden_field :delivery_reception_time_3_finish, :value => @store.store_order_info.delivery_reception_time_3_finish %><br />

          <%= i.label :delivery_reception_time_4 %>
          <%= @store.store_order_info.delivery_reception_time_4_first.to_s(:time) %>
          <%= i.hidden_field :delivery_reception_time_4_first, :value => @store.store_order_info.delivery_reception_time_4_first %>
          ~
          <%= @store.store_order_info.delivery_reception_time_4_finish.to_s(:time) %>
          <%= i.hidden_field :delivery_reception_time_4_finish, :value => @store.store_order_info.delivery_reception_time_4_finish %><br />

          <%= i.label :delivery_reception_time_5 %>
          <%= @store.store_order_info.delivery_reception_time_5_first.to_s(:time) %>
          <%= i.hidden_field :delivery_reception_time_5_first, :value => @store.store_order_info.delivery_reception_time_5_first %>

          ~
          <%= @store.store_order_info.delivery_reception_time_5_finish.to_s(:time) %>
          <%= i.hidden_field :delivery_reception_time_5_finish, :value => @store.store_order_info.delivery_reception_time_5_finish %><br />

          <%= i.label :delivery_reception_time_6 %>
          <%= @store.store_order_info.delivery_reception_time_6_first.to_s(:time) %>
          <%= i.hidden_field :delivery_reception_time_6_first, :value => @store.store_order_info.delivery_reception_time_6_first %>
          ~
          <%= @store.store_order_info.delivery_reception_time_6_finish.to_s(:time) %>
          <%= i.hidden_field :delivery_reception_time_6_finish, :value => @store.store_order_info.delivery_reception_time_6_finish %><br />

          <%= i.label :delivery_reception_time_7 %>
          <%= @store.store_order_info.delivery_reception_time_7_first.to_s(:time) %>
          <%= i.hidden_field :delivery_reception_time_7_first, :value => @store.store_order_info.delivery_reception_time_7_first %>
          ~
          <%= @store.store_order_info.delivery_reception_time_7_finish.to_s(:time) %>
          <%= i.hidden_field :delivery_reception_time_7_finish, :value => @store.store_order_info.delivery_reception_time_7_finish %><br />
        </td>
      </tr>

      <tr class="field">
        <td class="label"><%= i.label :comment %></td>
        <td class="field">
          <div class="store-confirm"><%= @store.store_order_info.comment %></div>
          <%= i.hidden_field :comment, :value => @store.store_order_info.comment %>
        </td>
      </tr>

    </table>

  <% end %>

  <div class="actions" id="store-submit">
    <%= f.submit '戻る', name: :back, class: "btn btn-secondary" %>
    <%= f.submit "登録", class: "btn btn-success" %>
  </div>

<% end %>

app/views/stores/edit.html.erb
<h2 class="page-title">店舗情報編集</h2>

<%= form_for(@store, url: store_path) do |f| %>

  <table class="store-form">
    <tr class="field">
      <td class="label"><%= f.label :store_name %><span>&nbsp※必須</span></td>
      <td class="field"><%= f.text_field :store_name, autofocus: true, autocomplete: "store_name", class: "store-input" %></td>
    </tr>

    <tr class="field">
      <td class="label"><%= f.label :phone_num %><span>&nbsp※必須</span></td>
      <td class="field"><%= f.text_field :phone_num, autofocus: true, autocomplete: "phone_num", class: "store-input" %></td>
    </tr>

    <tr class="field">
      <td class="label"><%= f.label :address %><span>&nbsp※必須</span></td>
      <td class="field address">
        <div class="">
          <%= f.label :post_code %>
          <%= f.text_field :post_code, autofocus: true, autocomplete: "post_code", class: "store-input-address" %>
        </div><br />
        <div class="">
          <%= f.label :prefecture_id %>
          <%= f.select :prefecture_id, Store.prefecture_ids.keys, {}, class: "store-input-address" %>
        </div><br />
        <div class="">
          <%= f.label :city %>
          <%= f.text_field :city, autofocus: true, autocomplete: "city", class: "store-input-address" %>
        </div><br />
        <div class="">
          <%= f.label :block %>
          <%= f.text_field :block, autofocus: true, autocomplete: "block", class: "store-input-address" %>
        </div><br />
        <div class="">
          <%= f.label :building %>
          <%= f.text_field :building, autofocus: true, autocomplete: "building", class: "store-input-address" %>
        </div>
      </td>
    </tr>

    <tr class="field">
      <td class="label"><%= f.label :business_hours %><span>&nbsp※必須</span></td>
      <td class="field">
        <%= f.time_field :business_hours_start, autofocus: true, autocomplete: "business_hours_start", class: "store-hours" %>
        ~
        <%= f.time_field :business_hours_finish, autofocus: true, autocomplete: "business_hours_finish", class: "store-hours" %>
      </td>
    </tr>

    <tr class="field">
      <td class="label"><%= f.label :holiday %><span>&nbsp※必須</span></td>
      <td class="field"><%= f.text_field :holiday, autofocus: true, autocomplete: "holiday", class: "store-input" %></td>
    </tr>

    <tr class="field">
      <td class="label"><%= f.label :home_url %></td>
      <td class="field"><%= f.text_field :home_url, autofocus: true, autocomplete: "home_url", class: "store-input" %></td>
    </tr>

  </table>

  <h2 class="page-title2">注文情報編集</h2>

  <%= f.fields_for :store_order_info do |i| %>

    <table class="store-form">

      <tr class="field">
        <td class="label"><%= i.label :reception_email %><span>&nbsp※必須</span></td>
        <td class="field"><%= i.email_field :reception_email, autofocus: true, autocomplete: "reception_email", class: "store-input" %></td>
      </tr>

      <tr class="field">
        <td class="label"><%= i.label :transport_fee %><span>&nbsp※必須</span></td>
        <td class="field"><%= i.text_field :transport_fee, autofocus: true, autocomplete: "transport_fee", class: "store-input-fee" %>円</td>
      </tr>

      <tr class="field">
        <td class="label"><%= i.label :delivery_reception_time %><span>&nbsp※必須</span></td>
        <td class="field delively_reception">
          <%= i.label :delivery_reception_time_1 %>
          <%= i.time_field :delivery_reception_time_1_first, autofocus: true, autocomplete: "delivery_reception_time_1", class: "store-hours" %>
          ~
          <%= i.time_field :delivery_reception_time_1_finish, autofocus: true, autocomplete: "delivery_reception_time_1", class: "store-hours" %><br />

          <%= i.label :delivery_reception_time_2 %>
          <%= i.time_field :delivery_reception_time_2_first, autofocus: true, autocomplete: "delivery_reception_time_2", class: "store-hours" %>
          ~
          <%= i.time_field :delivery_reception_time_2_finish, autofocus: true, autocomplete: "delivery_reception_time_2", class: "store-hours" %><br />

          <%= i.label :delivery_reception_time_3 %>
          <%= i.time_field :delivery_reception_time_3_first, autofocus: true, autocomplete: "delivery_reception_time_3", class: "store-hours" %>
          ~
          <%= i.time_field :delivery_reception_time_3_finish, autofocus: true, autocomplete: "delivery_reception_time_3", class: "store-hours" %><br />

          <%= i.label :delivery_reception_time_4 %>
          <%= i.time_field :delivery_reception_time_4_first, autofocus: true, autocomplete: "delivery_reception_time_4", class: "store-hours" %>
          ~
          <%= i.time_field :delivery_reception_time_4_finish, autofocus: true, autocomplete: "delivery_reception_time_4", class: "store-hours" %><br />

          <%= i.label :delivery_reception_time_5 %>
          <%= i.time_field :delivery_reception_time_5_first, autofocus: true, autocomplete: "delivery_reception_time_5", class: "store-hours" %>
          ~
          <%= i.time_field :delivery_reception_time_5_finish, autofocus: true, autocomplete: "delivery_reception_time_5", class: "store-hours" %><br />

          <%= i.label :delivery_reception_time_6 %>
          <%= i.time_field :delivery_reception_time_6_first, autofocus: true, autocomplete: "delivery_reception_time_6", class: "store-hours" %>
          ~
          <%= i.time_field :delivery_reception_time_6_finish, autofocus: true, autocomplete: "delivery_reception_time_6", class: "store-hours" %><br />

          <%= i.label :delivery_reception_time_7 %>
          <%= i.time_field :delivery_reception_time_7_first, autofocus: true, autocomplete: "delivery_reception_time_7", class: "store-hours" %>
          ~
          <%= i.time_field :delivery_reception_time_7_finish, autofocus: true, autocomplete: "delivery_reception_time_7", class: "store-hours" %>
        </td>
      </tr>

      <tr class="field">
        <td class="label"><%= i.label :comment %></td>
        <td class="field"><%= i.text_area :comment, autofocus: true, autocomplete: "comment", class: "store-input-comment" %></td>
      </tr>

    </table>

  <% end %>

  <div class="actions" id="store-submit">
    <%= f.submit '戻る', name: :back, class: "btn btn-secondary" %>
    <%= f.submit "変更する", class: "btn btn-success" %>
  </div>


<% end %>

app/views/stores/index.html.erb
<h1>Stores#index</h1>
<p>Find me in app/views/stores/index.html.erb</p>

app/views/stores/new.html.erb
<h2 class="page-title">店舗情報登録</h2>

<%= form_for(@store, url: confirm_stores_path) do |f| %>

  <table class="store-form">
    <tr class="field">
      <td class="label"><%= f.label :store_name %><span>&nbsp※必須</span></td>
      <td class="field"><%= f.text_field :store_name, autofocus: true, autocomplete: "store_name", class: "store-input" %></td>
    </tr>

    <tr class="field">
      <td class="label"><%= f.label :phone_num %><span>&nbsp※必須</span></td>
      <td class="field"><%= f.text_field :phone_num, autofocus: true, autocomplete: "phone_num", class: "store-input" %></td>
    </tr>

    <tr class="field">
      <td class="label"><%= f.label :address %><span>&nbsp※必須</span></td>
      <td class="field address">
        <div class="">
          <%= f.label :post_code %>
          <%= f.text_field :post_code, autofocus: true, autocomplete: "post_code", class: "store-input-address" %>
        </div><br />
        <div class="">
          <%= f.label :prefecture_id %>
          <%= f.select :prefecture_id, Store.prefecture_ids.keys, {}, class: "store-input-address" %>
        </div><br />
        <div class="">
          <%= f.label :city %>
          <%= f.text_field :city, autofocus: true, autocomplete: "city", class: "store-input-address" %>
        </div><br />
        <div class="">
          <%= f.label :block %>
          <%= f.text_field :block, autofocus: true, autocomplete: "block", class: "store-input-address" %>
        </div><br />
        <div class="">
          <%= f.label :building %>
          <%= f.text_field :building, autofocus: true, autocomplete: "building", class: "store-input-address" %>
        </div>
      </td>
    </tr>

    <tr class="field">
      <td class="label"><%= f.label :business_hours %><span>&nbsp※必須</span></td>
      <td class="field">
        <%= f.time_field :business_hours_start, autofocus: true, autocomplete: "business_hours_start", class: "store-hours" %>
        ~
        <%= f.time_field :business_hours_finish, autofocus: true, autocomplete: "business_hours_finish", class: "store-hours" %>
      </td>
    </tr>

    <tr class="field">
      <td class="label"><%= f.label :holiday %><span>&nbsp※必須</span></td>
      <td class="field"><%= f.text_field :holiday, autofocus: true, autocomplete: "holiday", class: "store-input" %></td>
    </tr>

    <tr class="field">
      <td class="label"><%= f.label :home_url %></td>
      <td class="field"><%= f.text_field :home_url, autofocus: true, autocomplete: "home_url", class: "store-input" %></td>
    </tr>

  </table>

  <h2 class="page-title2">注文情報</h2>

  <%= f.fields_for :store_order_info do |i| %>

    <table class="store-form">

      <tr class="field">
        <td class="label"><%= i.label :reception_email %><span>&nbsp※必須</span></td>
        <td class="field"><%= i.email_field :reception_email, autofocus: true, autocomplete: "reception_email", class: "store-input" %></td>
      </tr>

      <tr class="field">
        <td class="label"><%= i.label :transport_fee %><span>&nbsp※必須</span></td>
        <td class="field"><%= i.text_field :transport_fee, autofocus: true, autocomplete: "transport_fee", class: "store-input-fee" %>円</td>
      </tr>

      <tr class="field">
        <td class="label"><%= i.label :delivery_reception_time %><span>&nbsp※必須</span></td>
        <td class="field delively_reception">
          <%= i.label :delivery_reception_time_1 %>
          <%= i.time_field :delivery_reception_time_1_first, autofocus: true, autocomplete: "delivery_reception_time_1", class: "store-hours" %>
          ~
          <%= i.time_field :delivery_reception_time_1_finish, autofocus: true, autocomplete: "delivery_reception_time_1", class: "store-hours" %><br />

          <%= i.label :delivery_reception_time_2 %>
          <%= i.time_field :delivery_reception_time_2_first, autofocus: true, autocomplete: "delivery_reception_time_2", class: "store-hours" %>
          ~
          <%= i.time_field :delivery_reception_time_2_finish, autofocus: true, autocomplete: "delivery_reception_time_2", class: "store-hours" %><br />

          <%= i.label :delivery_reception_time_3 %>
          <%= i.time_field :delivery_reception_time_3_first, autofocus: true, autocomplete: "delivery_reception_time_3", class: "store-hours" %>
          ~
          <%= i.time_field :delivery_reception_time_3_finish, autofocus: true, autocomplete: "delivery_reception_time_3", class: "store-hours" %><br />

          <%= i.label :delivery_reception_time_4 %>
          <%= i.time_field :delivery_reception_time_4_first, autofocus: true, autocomplete: "delivery_reception_time_4", class: "store-hours" %>
          ~
          <%= i.time_field :delivery_reception_time_4_finish, autofocus: true, autocomplete: "delivery_reception_time_4", class: "store-hours" %><br />

          <%= i.label :delivery_reception_time_5 %>
          <%= i.time_field :delivery_reception_time_5_first, autofocus: true, autocomplete: "delivery_reception_time_5", class: "store-hours" %>
          ~
          <%= i.time_field :delivery_reception_time_5_finish, autofocus: true, autocomplete: "delivery_reception_time_5", class: "store-hours" %><br />

          <%= i.label :delivery_reception_time_6 %>
          <%= i.time_field :delivery_reception_time_6_first, autofocus: true, autocomplete: "delivery_reception_time_6", class: "store-hours" %>
          ~
          <%= i.time_field :delivery_reception_time_6_finish, autofocus: true, autocomplete: "delivery_reception_time_6", class: "store-hours" %><br />

          <%= i.label :delivery_reception_time_7 %>
          <%= i.time_field :delivery_reception_time_7_first, autofocus: true, autocomplete: "delivery_reception_time_7", class: "store-hours" %>
          ~
          <%= i.time_field :delivery_reception_time_7_finish, autofocus: true, autocomplete: "delivery_reception_time_7", class: "store-hours" %>
        </td>
      </tr>

      <tr class="field">
        <td class="label"><%= i.label :comment %></td>
        <td class="field"><%= i.text_area :comment, autofocus: true, autocomplete: "comment", class: "store-input-comment" %></td>
      </tr>

    </table>

  <% end %>

  <div class="actions" id="store-submit">
    <%= f.submit "内容確認", class: "btn btn-success" %>
  </div>


<% end %>