config/routes.rb
Rails.application.routes.draw do
  # トップページ
  root to: 'tops#index'

  # devise関連(shop_user)
  devise_for :shop_users, skip: :all

  devise_scope :shop_user do
    get 'login' => 'shop_users/sessions#new', as: :new_shop_user_session
    post 'login' => 'shop_users/sessions#create', as: :shop_user_session
    delete 'logout' => 'shop_users/sessions#destroy', as: :destroy_shop_user_session
    get 'signup' => 'shop_users/registrations#new', as: :new_shop_user_registration
    post "sign_up/confirm" => "shop_users/registrations#confirm", as: :confirm_shop_user_registration
    post 'signup' => 'shop_users/registrations#create', as: :shop_user_registration
    # get 'signup/cancel' => 'shop_users/registrations#cancel', as: :cancel_shop_user_registration
    get '/:shop_user_id/shop_user' => 'shop_users/registrations#show', as: :show_shop_user_registration
    get '/:shop_user_id/shop_user/edit' => 'shop_users/registrations#edit', as: :edit_shop_user_registration
    patch '/:shop_user_id/shop_user/update' => 'shop_users/registrations#update', as: :update_shop_user_registration
    # put 'user' => 'shop_users/registrations#update', as: :update_shop_user_registration
    delete 'user' => 'shop_users/registrations#destroy', as: :destroy_shop_user_registration
    get 'password' => 'shop_users/passwords#new', as: :new_shop_user_password
    post 'password' => 'shop_users/passwords#create', as: :shop_user_password
    get 'password/edit' => 'shop_users/passwords#edit', as: :edit_shop_user_password
    patch 'password' => 'shop_users/passwords#update'
    put 'password' => 'shop_users/passwords#update', as: :update_shop_user_password
  end
  resources :shop_users

  # 店舗関連
  controller :stores do
    scope path: ':shop_user_id' do
      resources :stores do
        post 'confirm', on: :collection
        # 店舗紐付きの商品関連
        resources :menus
      end
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light header-menu">
  <div class="collapse navbar-collapse" id="Navber">
    <ul class="navbar-nav mr-auto">
      <% unless shop_user_signed_in? %>
        <li class="nav-item">
          <%= link_to "店舗ログイン", new_shop_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "店舗登録", new_shop_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "利用マニュアル", "#", class: "nav-link" %>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "店舗トップ", stores_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "店舗情報登録", new_store_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <% if Store.current_store(current_shop_user).present? %>
          <%= link_to "商品登録", store_menus_path(store_id: current_shop_user.store.id), class: "nav-link" %>
        <% else %>
          <%= link_to "商品登録", stores_path, class: "nav-link" %>
        <% end %>
        </li>
        <li class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          店舗ユーザー
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "ユーザー設定", show_shop_user_registration_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "ログアウト", destroy_shop_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% end %>
    </ul>
</nav>

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: key) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeliveryServiceHelper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <!-- タイトル -->
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #FFFF99;">
      <% unless shop_user_signed_in? %>
        <%= link_to root_path, class: "navbar-brand" do %>
          <%= image_tag 'logo2.png'%>
        <% end %>
      <% else %>
        <%= link_to stores_path(current_shop_user), class: "navbar-brand" do %>
          <%= image_tag 'logo2.png'%>
        <% end %>
      <% end %>
    </nav>
    <!-- ヘッダー画像 -->
    <% if current_page?(root_path) %>
      <%= image_tag 'image01.jpg', class: "header-image" %>
    <% end %>
    <!-- ヘッダーメニュー -->
    <%= render 'layouts/header' %>
    <!-- flash -->
    <div class="notifications">
      <%= render 'layouts/notifications' %>
    </div>
    <!-- メインコンテンツ -->
    <div class="content">
      <%= yield %>
    </div>
    <!-- フッタ -->
    <%= render 'layouts/footer' %>
  </body>
</html>